### ISSUE TITLE
Push v0.9.10 to NPM

### ISSUE THREAD

**Issue by wingrunr21** [Download/memorystorage#1]
Hi,

Looks like v0.9.10 never got pushed to NPM. Would you mind doing that?

Thanks!

**Comment by Download** [comment]
Will do!

**Comment by Download** [comment]
[Done!](https://www.npmjs.com/package/memorystorage)

**Comment by Download** [comment]
@wingrunr21

**Comment by wingrunr21** [comment]
Thanks :+1:

**Comment by Download** [comment]
:+1: 

Let me know if it works out for you. Any problems? Just open a new issue.
