### ISSUE TITLE
Cannot find module memorystorage

### ISSUE THREAD

**Issue by daniel-seitz** [Download/memorystorage#11]
Hi, I'm confused about the documentation and different header sizes. I.e. where does 'Installation' end? My troubles could be because of this.

I did:

    npm install --save memorystorage

And then in my Angular CLI project ES2015:

    import MemoryStorage from 'memorystorage';
    ....
    this.storage = new MemoryStorage();

but my ng serve spits out `cannot find module 'memorystorage'`. It is there in my npm folder and other packages like moment work.

Also could be a Typescript issue, ... since that't not ES2015. 

In my package.json: `"memorystorage": "^0.11.0",`

Any ideas about this?

**Comment by Download** [comment]
Sorry I did not get time to look into this. If you are convinced this was a bug, let me know and I'll reopen this.
