### ISSUE TITLE
Invalid exports in package.json

### ISSUE THREAD

**Issue by matthemsteger** [Download/memorystorage#14]
With recent NPM and node updates, for example `node 12.18.0` and `npm 6.14.4`, there is a more strict check on the `package.json`.

```
Error [ERR_INVALID_PACKAGE_TARGET] [ERR_INVALID_PACKAGE_TARGET]: Invalid "exports" main target "MemoryStorage" defined in the package config /var/www/restref-site/node_modules/memorystorage/package.json; targets must start with "./"
```

This prevents the use of this package.

**Comment by Download** [comment]
PR welcome!

**Comment by Trukl** [comment]
here it is : https://github.com/Download/memorystorage/pull/16

**Comment by Download** [comment]
@CorentinMinne Great work and welcome on board!
I leave it to you to merge and create a new release.
