### ISSUE TITLE
Convert the library to a ECMAscript module instead of a CommonJS module

### ISSUE THREAD

**Issue by Maximaximum** [Download/memorystorage#15]
Rationale: https://web.dev/commonjs-larger-bundles/

**Comment by Download** [comment]
I'd be willing to review and merge the PR 👍

**Comment by Maximaximum** [comment]
After having spent a couple of hours to investigate this issue:
1. It's unclear whether it's ok just to convert this lib to an es6 module, or should we somehow provide it in both formats - UMD and ES6 - to the users
2. Even simply converting this lib to es6 is not trivial - I'm getting errors while trying to run tests, seems like we'll need to use a different test runner
3. Converting the lib to an ES6 module does not provide any real benefit in terms of bundle size, since the lib is tiny, and it anyway contains just a single exportable symbol.

Having said that, I'm not sure whether it makes sense to spend any more time on this issue. Please feel free to close it.

**Comment by Download** [comment]
I'm not actively using memorystorage in any of my current work, so I have no interest in spending much time on it atm. So I am closing this, but feel free to re-open if you change your mind.
