### ISSUE TITLE
If this allows me to use Session Storage like things across all the browsers, why would I use a switch case? Why not just use MemoryStorage the whole time in all situations? 

### ISSUE THREAD

**Issue by excenter** [Download/memorystorage#8]

**Comment by excenter** [comment]
I don't know if this is expected behavior, or just for the application I'm working on, but reloading the page nukes everything in MemoryStorage.... that's a reason.

**Comment by Download** [comment]
Sorry for not responding sooner... I see you already found the reason youself.

So what;s the point of this project then, you may ask? Well it's about uniformity of your (test) code. Being able to just *create* a new storage object and use it as if it was `localStorage` can be really convenient sometimes. I used it mostly for not having to deal with Safari private browsing mode nonsense :)
